# This is a basic workflow to help you get started with Actions

name: Build and Push docker image

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    tags:
      - '**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  push_to_registry:
    # The type of runner that the job will run on
    name: Push Docker image to Docker hub
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      # Runs a single command using the runners shell
      - name: Fetch tags
        id: prep
        run: |
          git fetch --tags
          latest_tag=$(git describe --tags --abbrev=0)
          echo "Hello world"
          echo ::set-output name=tags::${latest_tag}

      - name: get latest tag
        id: build
        run: |
          echo "The tag is ${{ steps.prep.outputs.tags}}"



