name: HelloWorld action
on:
  workflow_dispatch
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: hello world action step
        id: hello
        uses: openvmi/hello-world-docker-action@master
        with:
          who-to-greet: "Mona the octocat"
      - name: Get the output time
        run: |
          echo "The time was ${{ steps.hello.outputs.time }}"
          echo "CI: $CI"
          echo "GITHUB_WORKFLOW: $GITHUB_WORKFLOW"
          echo "GITHUB_RUN_ID: $GITHUB_RUN_ID"
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
        
