# This is a basic workflow to help you get started with Actions

name: Add tag and Build docker image

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  addTag:
    # The type of runner that the job will run on
    name: Add tag automatically
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.addtag.outputs.tag }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout source code
        uses: actions/checkout@v2
        id: clonecode
        with:
          fetch-depth: '0'

      # Runs a single command using the runners shell
      - name: Bump version and push tag
        id: addtag
        uses: openvmi/tag-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  buildImage:
    name: Build the docker image
    runs-on: ubuntu-latest
    needs: [addTag]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to ALiyun Registry
        uses: docker/login-action@v1
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_TOKEN }}
          
      - name: Get image tag
        id: getTag
        run: |
          tag=${{ needs.addTag.outputs.tag }}
          imageTag=$(tag#*-)
          echo "imageTag: ${imageTag}"
          echo ::set-output name=imageTag::${imageTag}
          
      - name: Build and push docker image
        id: build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.ALIYUN_REGISTRY}}:latest
            ${{ secrets.ALIYUN_REGISTRY}}:${${{}}}
